### ISSUE TITLE
Bug: Contao 3.2.16 + t4w 1.2.0

### ISSUE THREAD

**Issue by xantippe** [psi-4ward/table4ward#4]
Hallo,

ich habe das Release-Zip manuell installiert - Firebug bringt die Meldung:

```
"NetworkError: 404 Not Found - http://www.domain.de/contao/assets/tinymce4/tinymce.gzip.js"
```

ist die Version für 3.2 nicht frei gegeben?

**Comment by psi-4ward** [comment]
Use 1.1.2 for contao 3.2
