### ISSUE TITLE
Bug: Contao 3.3.7 + t4w 1.2 mit FF 33.03

### ISSUE THREAD

**Issue by xantippe** [psi-4ward/table4ward#5]
es kommt im FF folgender Fehler:
```
TypeError: Browser.Engine is undefined
http://www.domain.de/system/modules/table4ward/html/TableWizard4ward.js
Line 24
```

im Chrome gehts

**Comment by psi-4ward** [comment]
Contao 3.4 + FF 34 geht
sicher das du kein Cache Problem hast? Der Fehler ist schon lange behoben

**Comment by xantippe** [comment]
habe inzwischen auch FF 34.x - ohne Fehlermeldung...
