### ISSUE TITLE
Modal window & alert

### ISSUE THREAD

**Issue by planepix** [psi-4ward/table4ward#6]
Hi Psi,
got these errors under a 3.5.17 (also had these under 3.4 installations):

1. When doubleclick to a table cell the modal window with the Tiny opens elsewhere, mostly you need to scroll to the top left area to see the editor.
![table4ward-open](https://cloud.githubusercontent.com/assets/1823889/19704332/9bd89174-9b07-11e6-8298-ec3659d5dc56.png)

2. When click to ”save” or ”save and close” you get a message/ alert window to save before leaving the page. Edited content will be saved when clicked Save first and then cancel the alert window.
![alert](https://cloud.githubusercontent.com/assets/1823889/19704281/6b017aa2-9b07-11e6-8ea8-2eaf293f7295.png)

Any idea or time to fix this?
Thanx in advance
Thomas

**Comment by psi-4ward** [comment]
Not really. Can you give me a dump of the installation?

**Comment by planepix** [comment]
Sure, will setup one and send you the details. Tahnk you.

**Comment by planepix** [comment]
Package is ready bundled. You got mail. Thank you in advance.

**Comment by psi-4ward** [comment]
database-dump + contao install => zip ;)

Oder wir schauen uns das aufm Camp an

**Comment by planepix** [comment]
Yes, the link for the zip was included in my mail :-) or did i miss something?
