### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by p33k** [psi-4ward/table4ward#7]
Gibt es keine Version welche mit Contao 4 funktioniert?

**Comment by bibib** [comment]
Ich hänge mich mal dran ... wenn Anpassungen nötig sind, könnte man die beauftragen und was würde das kosten?

**Comment by psi-4ward** [comment]
Nuja ich bin aktuell nicht mehr wirklich in Contao (4) involviert wüsste gar nicht was da gemacht werden müsste. Natürlich könnten wir das über nen Auftrag abwickeln aber ich würde da sicher mehr Zeit brauchen als ein versierter Entwickler. Es haben sich auch schon ein paar Leute gemeldet welche die Erweiterungen übernehmen wollte aber das dürfte auch schon wieder über nem Jahr her sein.

**Comment by bibib** [comment]
Danke für die Info, dann frage ich mal im Forum!

**Comment by bibib** [comment]
Für alle, die nach einer Alternative suchen: [contao-rte_table](https://github.com/terminal42/contao-rte_table)
